sudo: required
dist: trusty
language: python
python: '3.7'

services:
  - docker

env:
  - IMAGE_NAME=docupdater/docupdater

install:
  - pip install --user -r requirements.txt
  - pip install --user -U flake8

before_script: []

script:
  - python -m flake8 --max-line-length 120 docupdater

before_deploy:
  - python setup.py bdist_wheel
  - docker build -f Dockerfile --pull --tag "docupdater/$TRAVIS_BRANCH" .
  - docker build -f Dockerfile.arm --pull --tag "docupdater/$TRAVIS_BRANCH-arm" .
  - docker build -f Dockerfile.arm64 --pull --tag "docupdater/$TRAVIS_BRANCH-arm64" .
