sudo: required
dist: xenial
language: python
python: 3.7

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y wget git
  - sudo apt-get remove docker-ce
  - echo "deb [arch=amd64 trusted=yes] http://ftp.unicamp.br/pub/linuxpatch/ubuntu/14_04/misc/docker-17.04.0-ce-amd64/ trusty main" | sudo tee /etc/apt/sources.list.d/docker-engine.list
  - sudo apt-get update
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo apt-get install -y docker-engine
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - wget https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/qemu-arm-static.tar.gz -O /tmp/qemu-arm-static.tar.gz
  - wget https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-arm-static.tar.gz -O /tmp/x86_64_qemu-arm-static.tar.gz

install:
  - pip install -r requirements.txt
  - pip install -U flake8

before_script:
  - python -m flake8 --max-line-length 120 docupdater

script:
  - python setup.py bdist_wheel
  - docker build -f Dockerfile --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH" .
  - tar zxvf /tmp/qemu-arm-static.tar.gz -C /tmp
  - docker build --volume type=bind,source=/tmp/qemu-arm-static,target=/usr/bin/qemu-arm-static -f Dockerfile.arm --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH-arm" .
  - tar zxvf /tmp/x86_64_qemu-arm-static.tar.gz -C /tmp
  - docker build --volume type=bind,source=/tmp/qemu-arm-static,target=/usr/bin/qemu-arm-static -f Dockerfile.arm64 --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH-arm64" .

before_deploy:
  - docker manifest create docupdater/docupdater:$TRAVIS_BRANCH docupdater/docupdater:$TRAVIS_BRANCH-amd64 docupdater/docupdater:$TRAVIS_BRANCH-arm64 docupdater/docupdater:$TRAVIS_BRANCH-arm

deploy:
  - provider: script
    script: docker manifest push -p docupdater/docupdater:$TRAVIS_BRANCH
    on:
      branch: master