sudo: required
dist: xenial
language: python
python: 3.7

env:
  global:
    secure: c6wQiwgTIO9NhBEgs3zdvtHQ1OLjXfJ7mPl07apRLBYQjtuyL7YuEgcS3/g90/5v/LIMV6lA9q+oZyG8m9vwS/Sm9nYuaNbaHyfYS1AS7rGzTyaVPZkctD2DtPD00/OSKJGjn64HNEnhHQajpPEHBayBKTnGXoofQyOGlLaAbIFEV/TzO4UV0Aw2cUnRfVIP6at8ESey6JU278dgGdFqBFJLOzpdEiiVLmpCmpUXgJZqQ3PDaLBf2iqFfimXni/tZt4hfDFh3Bz9rnBxKjOqnkjhYueIKz3VtLWiBE0SZ+/GAsbgl/v01IonKzXYo9izhhMK0m1js/taFLUuj13tUKLDBKtRcH4ZGXIaImYI/TG5pk9uGS9odhFiVjTQQ7rQ95ykbiUfSWksnTZB292m4ue1XhqVM8ugY6VuNBFSZc+EDOZZJTDPENP+ZpdOTY/Y5jZhxNruP68xT5O/X0MBF3d7K7O3sVaGlo6+lMDHPjZf0LMdQaOMvOn8RoVnKr8aNn06/ZuNZecmqX2Goo9hYR9bhIuTpXnBAFUF6RtU2A5gBf3rxr+B7efSB8l+8qjKo2aSS6tHeGagARimIThMuKE151F6qPrfamSDWM5axccpdxrbx8PjShw498b+/v4Uyl5Lt0jK4uBf8MVMhmXbVc7m3IbgZHhab1k9z62X8qM=

services:
  - docker

before_install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - sudo apt-get upgrade
  - sudo apt-get update
  - sudo apt-get install -qq -y qemu-user-static

install:
  - pip install -r requirements.txt

before_script:
  - python -m flake8 --max-line-length 120 docupdater

script:
  - python setup.py sdist bdist_wheel
  - docker build -f Dockerfile --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH-amd64" .
  - docker build -f Dockerfile.arm --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH-arm" .
  - docker build -f Dockerfile.arm64 --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH-arm64" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/release_deploy.sh
    on:
      tags: true
  - provider: pypi
    user: $PYPI_USERNAME
    password:
      secure: l4n2PpkbtiuyEsNkDX4oq5NKjDKYaOyT0HoovJY2QJeJu78/tWihxWYInE40YaExq1SbjXPr3Ufqny/TvaeAsQ43GpooE/4ueyLisR8V8msq6YrGGTmH1TtDFXM7x9rujdWYRuUBG2ry2O2SNWpM3aBXco/U0DeflbTujj3hhrXfjozWt3Hm1a9ToS3Z/saMYozL80G94xdX4LZ4BrJQZutlycsNYpK0LTDl/q/ILBuoOwyMB+/mi2dQD3ex93jWOUfyepff3SGjCMjH4JAbob0yT4Zq7tuyFeNICcNEocVgkt7+2h1Xr+erEbPTybKs46IF4jpu0kq9ln8PeRv8quHqEUUoHAsBoMGN7CHAedGRJTBv9tRXQf0JvkTrHYXsTckrkC11Lpse8OonTXN+QeNyUmbZzeR+y4sZsgt4icRUmutb2d3J0NSqdhfT6YRhPwUPgaSfnkLscwldV+eGi7QlIM1xTeszSY5yFOoJqGMLCIfc3kEkA/Mv/50JgSxpMHjG83+9GeaQ/LvNjuHzY6W1ZFb0PWIanV1OTWwE74QINxt4ngIv9aEuxnSouwTspuZVZScbmSnhJ7+vA3bvFS9ximsZq01eMVFf0qycdsVY+GRGNZ3OGw1CsPfShbQtWf45Ko1aPbXAKOy9DUYobnKt7hsXTZcLezknZBF6Ry8=
    on:
      tags: true