sudo: true
dist: xenial
language: python
python: 3.7

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -U flake8

before_script: []

script:
  - python -m flake8 --max-line-length 120 docupdater
  - python setup.py bdist_wheel

before_deploy:
  - docker build -f Dockerfile --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH" .
  - docker build -f Dockerfile.arm --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH-arm" .
  - docker build -f Dockerfile.arm64 --pull --tag "docupdater/docupdater:$TRAVIS_BRANCH-arm64" .
  - docker manifest create docupdater/docupdater:$TRAVIS_BRANCH docupdater/docupdater:$TRAVIS_BRANCH-amd64 docupdater/docupdater:$TRAVIS_BRANCH-arm64 docupdater/docupdater:$TRAVIS_BRANCH-arm

deploy:
  - provider: script
    script: docker manifest push -p docupdater/docupdater:$TRAVIS_BRANCH
    on:
      branch: master